FROM docker.elastic.co/kibana/kibana:7.9.0

USER root


RUN /usr/share/kibana/bin/kibana-plugin install https://github.com/nsano-rururu/elastalert-kibana-plugin/releases/download/1.3.0/elastalert-kibana-plugin-1.3.0-7.9.0.zip --allow-root

USER kibana
